spring:
  datasource:
    url: jdbc:mysql://192.168.163.111:3306/vipdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: admin321
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080